-- =============================================================================
-- 004_accounts.sql
-- Carries the two identifiers trade-api.yaml requires and are not interchangeable:
--   id         numeric surrogate key (ACCOUNTS.id). The int64 the contract path,
--              request body and JWT accountId claim all mean.
--   account_id customer-facing business reference (e.g. ACC-000001), returned as
--              AccountResponse.accountId and the dim_account natural key.
-- =============================================================================

CREATE TABLE accounts
(
    -- BY DEFAULT (not ALWAYS): the database assigns id when a row omits it (the
    -- Sprint 6 runtime path), but the CSV bulk-load may also supply explicit ids
    -- so that orders/positions/cash_ledger can reference their parent by the
    -- numeric surrogate. The Docker init hook resets the identity sequence after
    -- a CSV load; the .sql seed omits id and lets the database assign it.
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    account_id VARCHAR(32) NOT NULL UNIQUE,

    user_id UUID UNIQUE
        REFERENCES users(user_id),

    holder_name VARCHAR(255) NOT NULL,

    cash_balance DECIMAL(18,2) NOT NULL
        DEFAULT 0,

    currency CHAR(3) NOT NULL
        DEFAULT 'INR',

    -- Account state machine. Only ACTIVE may trade (rule 2, ACC-403).
    status account_status NOT NULL
        DEFAULT 'ACTIVE',

    -- Optimistic lock. Sprint 6 increments this on every write and rejects a
    -- stale update with ORD-409 (NFR-02).
    version INT NOT NULL
        DEFAULT 0,

    created_at TIMESTAMPTZ NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMPTZ NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_account_cash_non_negative
        CHECK (cash_balance >= 0),

    CONSTRAINT chk_account_currency
        CHECK (currency ~ '^[A-Z]{3}$')
);
