-- =============================================================================
-- 005_instruments.sql
-- A tradable instrument. symbol follows the Fauxnance scheme (.NS = NSE,
-- .BO = BSE, FX: = currency pair, X: = crypto, bare ticker = US venue). Delisting
-- is the tradable flag, never a delete: old orders still reference the row.
-- =============================================================================

CREATE TABLE instruments
(
    -- BY DEFAULT so the CSV bulk-load can supply explicit ids that orders,
    -- positions, watchlist_items and price_alerts reference. See accounts.id.
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    symbol VARCHAR(20) NOT NULL UNIQUE,

    name VARCHAR(255) NOT NULL,

    asset_class VARCHAR(20) NOT NULL,

    currency CHAR(3) NOT NULL
        DEFAULT 'INR',

    exchange VARCHAR(20),

    tradable BOOLEAN NOT NULL
        DEFAULT TRUE,

    created_at TIMESTAMPTZ NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_instrument_currency
        CHECK (currency ~ '^[A-Z]{3}$')
);
